on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/0aa6046728157b265a5af64f30644dfb
          gist_title: 1-Blink_LED-CCS.c
          gist_description: Prácticas PIC CCS
          github_file: Proyecto/PIC18F4550/Blink led.c
          file_encoding: WINDOWS-1252
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/a9d43bd831eb9bf83e4815f6e5be8447
          gist_title: 1-Blink_LED-CCS_18F45K50.c
          gist_description: Prácticas PIC CCS
          github_file: Proyecto/PIC18F45K50/Blink LED.c
          file_encoding: WINDOWS-1252